### ISSUE TITLE
Problem loggin on to Genenetwork2

### ISSUE THREAD

**Issue by JasFleet** [genenetwork/genenetwork2#444] opened 2020-09-18 14:44 UTC
I can't get logged into Genenetwork 2.

I'm using Firefox.   When I log in I get the error in the attached screen shot.    

![Screenshot 2020-09-18 08 59 04](https://user-images.githubusercontent.com/63613119/93610680-5f292300-f99b-11ea-8bfa-7b9f10addfbe.png)

**Comment by zsloan** [comment] 2020-09-18 15:45
I'll take a look at this and will probably be able to fix whatever the
issue is today.

**Comment by JasFleet** [comment] 2020-09-18 16:00
Thanks!

James C. Fleet PhD
Professor, Department of Nutrition Science
Purdue University
700 West State Street
West Lafayette, IN 47906-2059
(F) 1-765-494-0906
(Lab) 1-765-496-6055
fleet@purdue.edu

**Comment by zsloan** [comment] 2020-09-21 17:50
Could you try logging in again and, after getting the error, clicking "Toggle full stack trace" and sending a screenshot of that?

Also, what e-mail are you using to log-in? The issue seems to be specific to your account, so it's probably having an issue with some field.

**Comment by JasFleet** [comment] 2020-09-22 21:28
Here’s the screenshot.

Since this appears to be a problem with my account, would it be easier to just clear my information and have me start over? I have had the account for a while but I haven’t uploaded much or any data.   I don’t think it would set me back to do this.

Jim

James C. Fleet PhD
Professor, Department of Nutrition Science
Purdue University
700 West State Street
West Lafayette, IN 47906-2059
(F) 1-765-494-0906
(Lab) 1-765-496-6055
fleet@purdue.edu

**Comment by zsloan** [comment] 2020-09-22 21:42
Re-creating the account is probably a good idea. There were actually apparently two accounts associated with your e-mail (which isn't possible anymore but would have been possible in the past, though I'm not sure if that's the cause of this issue).

I removed those accounts, so you should be able to create a new account now. Let me know if you still run into a problem after that.

**Comment by JasFleet** [comment] 2020-09-22 22:13
Resetting was a good thing….I was able to get in the GeneNetwork2.

Out of curiosity, should the password work on both GN 1 and 2?

Jim

James C. Fleet PhD
Professor, Department of Nutrition Science
Purdue University
700 West State Street
West Lafayette, IN 47906-2059
(F) 1-765-494-0906
(Lab) 1-765-496-6055
fleet@purdue.edu

**Comment by zsloan** [comment] 2020-09-22 22:57
No, they have separate systems for storing users. Entering data into GN1
will still work for GN2 since they share a database, though (adding an
interface for entering data into GN2 is one of the higher priority things
we're planning on doing soon).

The main reasons someone would want to log into GN2 right now are for
controlling access to data resources (or being granted access by a resource
owner) and allowing collections to be stored across different computers.

The one unavoidable issue related to the new user/authorization system is
that ownership of data that was entered before we set up the authorization
system would need to be assigned to the corresponding GN2 user (if someone
wanted to access the authorization settings in GN2). For the time being Rob
or I can easily do that as long as the user account exists.

**Comment by BonfaceKilz** [comment] 2020-10-12 22:39
This seems to be resolved so I'm going ahead to close this.

**Closed as completed by BonfaceKilz** 2020-10-12 22:40 UTC
Labels: bug, High priority
