### ISSUE TITLE
Consistency regarding JS libraries

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork2#18] opened 2015-05-07 16:15 UTC
_From @lomereiter on May 6, 2015 10:26_

`jQuery` and `D3.js` are fetched from external websites, while most other libraries are stored locally

Estimated time/difficulty: Easy

_Copied from original issue: zsloan/genenetwork2#17_

**Comment by pjotrp** [comment] 2015-05-08 19:36
Needs to be running from the same webserver. Don't add the libraries to the git tree.

**Comment by pjotrp** [comment] 2018-04-02 08:38
Duplicate of #135

**Closed by pjotrp** 2018-04-02 08:38 UTC
Labels: Low priority, User interface, deployment
