### ISSUE TITLE
Some more issues with correlation

### ISSUE THREAD

**Issue by squirrelB** [genenetwork/genenetwork2#507] opened 2020-12-07 17:37 UTC
Hi,
Beni again.
About the correlation result: downloading results is now resolved. Thanks

But couple of issues I noted. First, the "sample r" used to be linked and clicking that opened a scatterplot. That's gone.

Another issue is related to the way the results are presented. To replicate this issue, try this (I'm working with the "BXD NIA Longevity Study" cohort, but this case is also seen with the BXDs)
1) Take BXD trait https://genenetwork.org/show_trait?trait_id=10015&dataset=BXDPublish as example. 
2) Perform correlation for the top 2000 using the dataset: NIA Aging BXD CD+HFD Liver RNA-Seq (Aug18) RPKM Log2 
3) Look at the top transcripts in the correlation results (i.e., "Index" 1, 2, etc). Those are not even significant... these are clearly not the top correlates.
4) Now download the data, and sort the results by "index". Doing so will list the top correlates. 
When downloaded, the "index" lists the genes by the most significant correlation. But in the scroller window, for some reason, the top genes rank pretty low as correlates. I think in the scroller window, the "index" should be fixed and kept to show most significant results.

**Comment by zsloan** [comment] 2020-12-07 18:13
Ah, those shouldn't be too hard to fix (probably in the next couple hours).

**Comment by zsloan** [comment] 2020-12-07 20:27
I just pushed changes. The issue with the sort is that it wasn't sorting
using scientific notation, and the scatterplot link just wasn't reproduced
when the table was redone (but wasn't hard to add back in).

**Comment by fredmanglis** [comment] 2022-03-23 05:47
@zsloan @squirrelB Is this issue fixed? It looks like @zsloan got some work done, but there has not been any more information since.

I am closing this for now, but if it is not fixed, please reopen with more notes, so that I know to migrate it to the new issue tracker.

**Closed as completed by fredmanglis** 2022-03-23 05:47 UTC
